=== IvanLapunka/epam-web-dev-task1/data/example.xsd
<?xml version = "1.0"  encoding="UTF-8"?>

<xs:schema xmlns:xs = "http://www.w3.org/2001/XMLSchema"
           targetNamespace = "http://www.example.org/gems"
           xmlns:tns = "http://www.example.org/gems"
           elementFormDefault = "qualified">


   <xs:element name="name" type="tns:Name"/>
   <xs:element name="origin" type="tns:Origin"/>
   <xs:element name="color" type="tns:Color"/>
   <xs:element name="transparency" type="tns:Transparency"/>
   <xs:element name="cutting" type="tns:Cutting"/>
   <xs:element name="weight" type="tns:Weight"/>
   <xs:element name="beauty" type="tns:Beauty"/>
   <xs:element name="get-date" type="xs:date"/>

   <xs:element name="gem" type="tns:Gem" abstract="true"/>
   <xs:element name="precious" type="tns:Precious" substitutionGroup="tns:gem"/>
   <xs:element name="semi-precious" type="tns:Semi-precious" substitutionGroup="tns:gem"/>

   <xs:element name="gems" type="tns:Gems"/>

   <xs:simpleType name="Name">
      <xs:restriction base="xs:string">
         <xs:maxLength value="100"/>
      </xs:restriction>
   </xs:simpleType>

   <xs:simpleType name="Origin">
      <xs:restriction base="xs:string">
         <xs:enumeration value="Australia and Oceania"/>
         <xs:enumeration value="Asia"/>
         <xs:enumeration value="America"/>
         <xs:enumeration value="Africa"/>
         <xs:enumeration value="Europe"/>
      </xs:restriction>
   </xs:simpleType>

   <xs:simpleType name="Color">
      <xs:restriction base="xs:string">
         <xs:enumeration value="Black"/>
         <xs:enumeration value="Red"/>
         <xs:enumeration value="Yellow"/>
         <xs:enumeration value="Green"/>
         <xs:enumeration value="Purple"/>
      </xs:restriction>
   </xs:simpleType>

   <xs:simpleType name="Transparency">
      <xs:restriction base="xs:int">
         <xs:minInclusive value="0"/>
         <xs:maxInclusive value="100"/>
      </xs:restriction>
   </xs:simpleType>

   <xs:simpleType name="Cutting">
      <xs:restriction base="xs:int">
         <xs:minInclusive value="4"/>
         <xs:maxInclusive value="15"/>
      </xs:restriction>
   </xs:simpleType>

   <xs:simpleType name="Weight">
      <xs:restriction base="xs:double">
         <xs:minInclusive value="0.1"/>
         <xs:maxInclusive value="1000"/>
      </xs:restriction>
   </xs:simpleType>

   <xs:simpleType name="GemId">
      <xs:restriction base="xs:ID">
         <xs:pattern value="[A-Z]{4}\d{8}"/>
      </xs:restriction>
   </xs:simpleType>

   <xs:simpleType name="Quality">
      <xs:restriction base="xs:string">
         <xs:enumeration value="high"/>
         <xs:enumeration value="low"/>
         <xs:enumeration value="middle"/>
      </xs:restriction>
   </xs:simpleType>

   <xs:simpleType name="Beauty">
      <xs:restriction base="xs:string">
         <xs:enumeration value="fine"/>
         <xs:enumeration value="lovely"/>
         <xs:enumeration value="gorgeous"/>
      </xs:restriction>
   </xs:simpleType>

   <xs:complexType name="Gem">
      <xs:sequence>
         <xs:element ref="tns:name"/>
         <xs:element ref="tns:origin"/>
         <xs:element ref="tns:color"/>
         <xs:element ref="tns:transparency"/>
         <xs:element ref="tns:weight"/>
      </xs:sequence>
      <xs:attribute name="id" type="tns:GemId" use="required"/>
      <xs:attribute name="valuable" type="xs:boolean" default="true"/>
      <xs:attribute name="quality" type="tns:Quality" use="optional"/>
   </xs:complexType>

   <xs:complexType name="Semi-precious">
      <xs:complexContent>
         <xs:extension base="tns:Gem">
            <xs:sequence>
               <xs:element ref="tns:beauty"/>
            </xs:sequence>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>

   <xs:complexType name="Precious">
      <xs:complexContent>
         <xs:extension base="tns:Gem">
            <xs:sequence>
               <xs:element ref="tns:cutting"/>
               <xs:element ref="tns:get-date"/>
            </xs:sequence>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>

   <xs:complexType name="Gems">
      <xs:sequence>
         <xs:element ref="tns:gem" minOccurs="8" maxOccurs="unbounded"/>
      </xs:sequence>
   </xs:complexType>

</xs:schema>

=== IvanLapunka/epam-web-dev-task1/test_data/example.xml
<?xml version="1.0" encoding="utf-8"?>
<gems xmlns="http://www.example.org/gems"
      xsi:schemaLocation="http://www.example.org/gems example.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <precious id="AAAA10621231" valuable="true">
        <name>Agate</name>
        <origin>America</origin>
        <color>Green</color>
        <transparency>79</transparency>
        <weight>376.3</weight>
        <cutting>12</cutting>
        <get-date>1980-01-13</get-date>
    </precious>
    <precious id="AAAA30743074" valuable="false">
        <name>Amethyst</name>
        <origin>America</origin>
        <color>Black</color>
        <transparency>89</transparency>
        <weight>476</weight>
        <cutting>10</cutting>
        <get-date>1994-02-12</get-date>
    </precious>
    <semi-precious id="LLLL20682068" valuable="true" quality="middle">
        <name>Onyx</name>
        <origin>Africa</origin>
        <color>Black</color>
        <transparency>26</transparency>
        <weight>787</weight>
        <beauty>lovely</beauty>
    </semi-precious>
    <semi-precious id="MMMM45434543" valuable="true" quality="high">
        <name>Amber</name>
        <origin>America</origin>
        <color>Red</color>
        <transparency>24</transparency>
        <weight>629</weight>
        <beauty>gorgeous</beauty>
    </semi-precious>
</gems>

=== IvanLapunka/epam-web-dev-task1/data/example.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<gems xmlns="http://www.example.org/gems"
      xsi:schemaLocation="http://www.example.org/gems example.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <precious id="AAAA10621231" valuable="true">
        <name>Agate</name>
        <origin>America</origin>
        <color>Green</color>
        <transparency>79</transparency>
        <weight>376.3</weight>
        <cutting>12</cutting>
        <get-date>1980-01-13</get-date>
    </precious>
    <precious id="AAAA30743074" valuable="false">
        <name>Amethyst</name>
        <origin>America</origin>
        <color>Black</color>
        <transparency>89</transparency>
        <weight>476</weight>
        <cutting>10</cutting>
        <get-date>1994-02-12</get-date>
    </precious>
    <precious id="BBBB22572257" valuable="false">
        <name>Aquamarine</name>
        <origin>Africa</origin>
        <color>Yellow</color>
        <transparency>50</transparency>
        <weight>231</weight>
        <cutting>10</cutting>
        <get-date>1979-05-03</get-date>
    </precious>
    <precious id="CCCC19651965" valuable="true">
        <name>Sapphire</name>
        <origin>America</origin>
        <color>Yellow</color>
        <transparency>43</transparency>
        <weight>606.5</weight>
        <cutting>14</cutting>
        <get-date>2017-08-27</get-date>
    </precious>
    <semi-precious id="DDDD12141214" valuable="false">
        <name>Moonstone</name>
        <origin>Asia</origin>
        <color>Red</color>
        <transparency>2</transparency>
        <weight>750</weight>
    </semi-precious>
    <semi-precious id="EEEE45645645" valuable="true" quality="high">
        <name>Quartz</name>
        <origin>Asia</origin>
        <color>Green</color>
        <transparency>20</transparency>
        <weight>440</weight>
    </semi-precious>
    <precious id="FFFF12312232" valuable="false">
        <name>Diamond</name>
        <origin>America</origin>
        <color>Red</color>
        <transparency>71</transparency>
        <weight>969</weight>
        <cutting>10</cutting>
        <get-date>1998-05-04</get-date>
    </precious>
    <semi-precious id="GGGG21592159" valuable="false">
        <name>Zircon</name>
        <origin>America</origin>
        <color>Green</color>
        <transparency>5</transparency>
        <weight>306.9</weight>
    </semi-precious>
    <semi-precious id="LLLL20682068" valuable="true" quality="middle">
        <name>Onyx</name>
        <origin>Africa</origin>
        <color>Black</color>
        <transparency>26</transparency>
        <weight>787</weight>
    </semi-precious>
    <precious id="KKKK24992499" valuable="false" quality="low">
        <name>Emerald</name>
        <origin>Australia and Oceania</origin>
        <color>Purple</color>
        <transparency>54</transparency>
        <weight>825.1</weight>
        <cutting>6</cutting>
        <get-date>1986-04-01</get-date>
    </precious>
    <semi-precious id="MMMM45434543" valuable="true" quality="high">
        <name>Amber</name>
        <origin>America</origin>
        <color>Red</color>
        <transparency>24</transparency>
        <weight>629</weight>
    </semi-precious>
</gems>
